In [1]:
import numpy as np 
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
X, y = mnist["data"], mnist["target"]
y = y.astype(np.uint8)
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

C:\Users\none_void\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\none_void\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [57]:
y_train_5 = (y_train == 5) # True bei allen 5en, False bei allen anderen Ziffern.
y_test_5 = (y_test == 5)
y_train_5[y_train_5==True]=1
y_train_5[y_train_5==False]=0
y_train_5

0        1
1        0
2        0
3        0
4        0
        ..
59995    0
59996    0
59997    1
59998    0
59999    0
Name: class, Length: 60000, dtype: object

In [79]:
from MLPClassifier import MLPClassifier
model = MLPClassifier((5,5,5,5),alpha=0.01,max_iter=5000,mode="softmax")
X_train_scaled = X_train/255

In [80]:
model.fit(X_train_scaled,y_train_5.values)

In [81]:
model.cost_function

11223.364229189263

In [75]:
model.sigmoid[:,59956]

array([0.90939254, 0.09060746])

In [68]:
y_train_5[y_train_5==True]

0        1
11       1
35       1
47       1
65       1
        ..
59956    1
59960    1
59968    1
59993    1
59997    1
Name: class, Length: 5421, dtype: object

In [83]:
y_predict=model.predict(X_train_scaled)

In [84]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_train_5,y_predict)

0.06656666666666666

In [98]:
d= y_train_5.values 
d

array([1, 0, 0, ..., 1, 0, 0], dtype=object)

In [99]:
d = d.astype(np.uint8)

In [101]:
from sklearn.metrics import confusion_matrix
confusion_matrix(d,y_predict)

array([[52884,  1695],
       [ 2299,  3122]], dtype=int64)